Update share button functionality to show android share sheet
PatilShreyas/Foodium pull request #50
Opened 2020-12-01 20:37 UTC by meets7

**- Summary**
Use the Android Sharesheet to provide the share functionality, allowing for a more modern looking share menu on Android 10 (API level 29) and above. This will also add the ability to show rich content to previews.

**- Description for the changelog**
Handles the share action by creating an Intent with `ACTION_SEND` and uses the `Intent.createChooser` to return a share sheet intent. 

**- A picture or screenshot regarding change (not mandatory but encouraged)**
On Android 10,
<img src="https://user-images.githubusercontent.com/6688825/100489972-65472880-30dd-11eb-8d76-28069b1a23c4.png" height=300 width=150>

On Android 6,
<img src="https://user-images.githubusercontent.com/6688825/100793910-772d1200-33e2-11eb-9780-fa720d5c1334.png" height=300 width=150>

Closes #48

2020-12-02 00:26 UTC, meets7 commented
`./gradlew ktlintCheck` does not seem to return any errors locally. Unable to figure out the ktlint check. Any thoughts? @PatilShreyas

2020-12-02 02:58 UTC, PatilShreyas requested changes
@meets7 Thanks for this PR 😀. Few comments then I'll be happy to merge it.

2020-12-02 02:58 UTC, PatilShreyas commented on app/src/main/java/dev/shreyaspatil/foodium/ui/details/PostDetailsActivity.kt
> +                ?: throw IllegalArgumentException("`postId` must be non-null")
@meets7 Indentation here causing error, please use previous indentation.

2020-12-02 02:58 UTC, PatilShreyas commented on app/src/main/java/dev/shreyaspatil/foodium/ui/details/PostDetailsActivity.kt
> +            ActivityPostDetailsBinding.inflate(layoutInflater)
Here too

2020-12-02 02:58 UTC, PatilShreyas commented on app/src/main/java/dev/shreyaspatil/foodium/ui/details/PostDetailsActivity.kt
> +    private fun showShareTray() {
@meets7 keep function name as `share()`

2020-12-02 02:58 UTC, PatilShreyas commented on app/src/main/java/dev/shreyaspatil/foodium/ui/details/PostDetailsActivity.kt
> +        val intent = Intent(Intent.ACTION_SEND)
Here we can use `ShareCompat` which was used earlier to generate intent. Please refer previous revision.

2020-12-02 02:58 UTC, PatilShreyas commented on app/src/main/java/dev/shreyaspatil/foodium/ui/details/PostDetailsActivity.kt
> +            ActivityPostDetailsBinding.inflate(layoutInflater)
Indentation here causing lint issues, please remove that extra tab space.

2020-12-02 02:58 UTC, PatilShreyas commented on app/src/main/java/dev/shreyaspatil/foodium/ui/details/PostDetailsActivity.kt
> +                ?: throw IllegalArgumentException("`postId` must be non-null")
Indentation here causing lint issues, please remove that extra tab space.

2020-12-02 07:28 UTC, PatilShreyas commented
@meets7 You can know more about those errors on the link: https://github.com/PatilShreyas/Foodium/pull/50/checks?check_run_id=1482664720

***Fix issues listed here:***

![image](https://user-images.githubusercontent.com/19620536/100841914-01867c00-349e-11eb-8c09-7142f41065ee.png)

2020-12-03 11:31 UTC, merged

2020-12-03 11:32 UTC, PatilShreyas commented
Thanks, @meets7 for this PR! I've merged it. Feel free to contribute again!